AWSTemplateFormatVersion: '2010-09-09'
Description: Foundation stack creates SSM Parameter Store entries for the mtwa database config

Parameters:
  
  StackName:
    Type: String
    Description: Name of the  stack

Resources:

  DBSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${StackName}"
      Description: Database master password for the mtwa application
      GenerateSecretString: 
        SecretStringTemplate: !Sub '{"username": "administrator"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '\/@" '

  DBNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtwa/db/name
      Type: String
      Value: mtwadb

  DBEngineParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtwa/db/engine
      Type: String
      Value: MySQL
  
  DBPortParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtwa/db/port
      Type: String
      Value: 3306

Outputs:

  DBSecretId:
    Description: The password for the database
    Value: !Ref DBSecrets
    Export:
      Name: !Sub "${StackName}-DBSecretId"

  DBNameId:
    Description: The name for the database
    Value: !Ref DBNameParameter
    Export:
      Name: !Sub "${StackName}-DBNameId"

  DBEngineId:
    Description: The engine for the database
    Value: !Ref DBEngineParameter
    Export:
      Name: !Sub "${StackName}-DBEngineId"

  DBPortId:
    Description: The port for the database
    Value: !Ref DBPortParameter
    Export:
      Name: !Sub "${StackName}-DBPortId"

